variables:      # pipeline-level
  pipelineVersionFromCode: '---'
  versionFromCode: 'xxx'

trigger: 
    none

stages:
- stage: Prep
  jobs:
  - job: GetVersion
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: none

    - task: PowerShell@2
      displayName: Get the version from directory.builds.props
      name: setVariableStep
      inputs:
        targetType: 'inline'
        script: |
          [string] $version = $env:originVersion 
          Write-Host "Updating the value of the buildVersion to '$version'."
          Write-Host "##vso[task.setvariable variable=versionFromCode;isOutput=true;]$version";
          Write-Host "##vso[task.setvariable variable=pipelineVersionFromCode;isOutput=true;]$version";

    - task: PowerShell@2
      displayName: Show the version
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Current versionFromCode is '$($env:versionFromCode)'."
          Write-Host "Current pipelineVersionFromCode is '$($env:pipelineVersionFromCode)'."

  - job: TestingVariables
    dependsOn: GetVersion
    pool:
      vmImage: 'windows-latest'
    variables:
      someVersion:  $[dependencies.GetVersion.outputs['setVariableStep.pipelineVersionFromCode']
      testVersion:  $[counter(variables[dependencies.GetVersion.outputs['versionFromCode']], 0)]
    steps:
    - checkout: none
    - task: PowerShell@2
      displayName: Set the name of the build
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "Current testversion is '$(testVersion)'."
          Write-Host "Current someVersion is '$(someVersion)'."
          Write-Host "Current pipelineVersionFromCode is '$[dependencies.GetVersion.outputs['setVariableStep.versionFromCode']]'."
          Write-Host "Current pipelineVersionFromCode is '$(dependencies.GetVersion.outputs['setVariableStep.pipelineVersionFromCode'])'."
