trigger: 
    none

pool:
  vmImage: 'windows-latest'

variables:
  versionSuffix: 'ci.$(Build.BuildId)+Extended-MetaData'  
  Version: '1.2.3.4.5.6'
  solution: 'VersionTest/VersionTest.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  task: 'sometesttask'

steps:
  - checkout: self

  - task: NuGetToolInstaller@1
    displayName: Installing Nuget tools

  - task: NuGetCommand@2
    displayName: Restoring Nuget packages
    inputs:
      restoreSolution: '$(solution)'

  - task: MSBuild@1
    displayName: Building the solution
    inputs:
      solution: '$(solution)'
      msbuildArchitecture: 'x64'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      msbuildArguments: '-property:versionsuffix=$(versionSuffix)'

  - task: CopyFiles@2
    inputs:
      contents: ' **\bin\**'
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

