trigger: 
    none

parameters:
- name: channelName
  displayName: Build Channel Name
  type: string
  default: DEV
  values:
  - DEV
  - CI
  - Release

stages:
- stage: Prep
  jobs:
  - job: BuildSolution
    pool:
      vmImage: 'windows-latest'
    variables:
      channelTemp: ${{ parameters.channelName }}
      channel: $[lower(variables['channelTemp'])]
      versionSuffix: '$(channel).$(Build.BuildId)+Extended-MetaData'  
      archiveFile: '$(channel).$(Build.BuildId).zip'
      solution: 'VersionTest/VersionTest.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - checkout: self

    - task: NuGetToolInstaller@1
      displayName: Installing Nuget tools

    - task: NuGetCommand@2
      displayName: Restoring Nuget packages
      inputs:
        restoreSolution: '$(solution)'

    - task: MSBuild@1
      displayName: Building the solution
      inputs:
        solution: '$(solution)'
        msbuildArchitecture: 'x64'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        msbuildArguments: '-property:versionsuffix=$(versionSuffix)'

    - task: CopyFiles@2
      inputs:
        contents: ' **\bin\**'
        targetFolder: $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

    - task: ArchiveFiles@2
      displayName: Creating zip archive
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: true 
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(archiveFile)'
        replaceExistingArchive: true

    - task: AzureFileCopy@3
      displayName: Uploading the binaries to Azure
      inputs:
        SourcePath: '$(Build.ArtifactStagingDirectory)/$(archiveFile)'
        ConnectedServiceNameARM: 'Azure Enterprise'
        Destination: 'AzureBlob'
        StorageAccountRM: 'ultimaterails'
        ContainerName: 'devtest'
